.travis.yml, requirements.txt, setup.py, tests/test_it.py
Issue #5
Configure Travis CI and prepare a dummy library and versioning schema before the initial import.
Currently, under my personal account (nolar), with the permissions granted to other maintainers as needed.
Tasks after the merge:
=> Enable Travis with an empty library

kopf/reactor/queueing.py
> Issues: #10
There is an exception sporadically happening for the objects:
```
Traceback (most recent call last):
………
File "/usr/local/lib/python3.7/dist-packages/kopf/reactor/queueing.py", line 83, in watcher
key = (resource, event['object']['metadata']['uid'])
KeyError: 'uid'
```
It is, in turn, is caused by the unexpected event types coming from the Kubernetes API, specifically from the watch call (note that the object has the metadata, but no uid or standard k8s-object fields):
```python
{'object': {'apiVersion': 'v1',
'code': 410,
'kind': 'Status',
'message': 'too old resource version: 190491269 (208223535)',
'metadata': {},
'reason': 'Gone',
'status': 'Failure'},
'raw_object': {'apiVersion': 'v1',
'code': 410,
'kind': 'Status',
'message': 'too old resource version: 190491269 …
```
=> React on the errors and unknown events from k8s API

kopf/reactor/handling.py, kopf/structs/diffs.py
The diff field for the `@kopf.on.field` handler contains the whole obj diff, but should contain the field diff: i.e. only the records related to the handled field, with the field names relative to the field's root, not to the object's root.
> Issue : #21
=> Pass the field diff to the field handlers, not the obj diff

requirements.txt, tests/conftest.py, tests/test_async.py
> Issue : #13 (needed for #25)
Since Kopf is mostly asyncio-based, there will be a lot of async/await & asyncio tests, which also do the asyncio mocks. They behave differently than the regular (sync) tests & mocks, so some little magic is needed to enable them.
Here, we configure the asyncio environment to transparently run all `async def` test-functions as the asyncio tests, and the `mocker` fixture to support the async-compatible `CoroutineMock`.
These changes do not belong to any other task-specific PR, as they are generic.
=> Enable asyncio tests & mocks

kopf/reactor/queueing.py, kopf/reactor/watching.py, tests/test_streaming.py
Prevent the operator from freezing on the end of the watch-event stream.
> Issue : #25 
Python3 has issues with `StopIteration` exception from inside the async coroutines. This issue is addressed in [PEP-479](https://www.python.org/dev/peps/pep-0479/).
Briefly, this code works and raises a `RuntimeError` as per PEP-479:
```
import asyncio
async def fn(src):
print(next(src))
print(next(src))  # raises StopIteration
loop = asyncio.get_event_loop()
coro = fn(iter([100]))
loop.run_until_complete(coro)
```
```
RuntimeError: coroutine raised StopIteration
```
But this code prints an exception and hangs forever (here, we execute synchronous `next` in a thread pool aka asyncio "executor"):
```
import asyncio
async def fn(src):
print(await loop.run_in_executor(None, next, src))
print(await …
```
=> Replace built-in StopIteration with custom StopStreaming for API calls

kopf/__init__.py, kopf/reactor/registry.py, tests/basic-structs/test_cause.py, tests/basic-structs/test_handler.py, tests/basic-structs/test_resource.py, tests/conftest.py, tests/registries/conftest.py, tests/registries/test_creation.py, tests/registries/test_decorators.py, tests/registries/test_default_registry.py, tests/registries/test_global_registry.py, tests/registries/test_handler_matching.py, tests/registries/test_id_detection.py, tests/registries/test_registering.py
These tests "freeze" the public interface of the library regarding the registries and matching of handlers  by causes (i.e. resources-events-fields) — to prevent accidental regressions.
> Issue : #13
=> Test registry and matching of handlers by causes

docs/peering.rst, kopf/cli.py, kopf/reactor/peering.py, kopf/reactor/queueing.py
> Issue : #33 (only if appropriate)
@nolar I will write the tests and document it once we agreed on the implementation.
=> [GH-33] implement auto detection mode for peering.

LICENSE, README.md, setup.py
> Issue : #12 
PyPI now renders the README (long_description) improperly. It needs some hinting on the content type. 
The links must be absolute, as they are shown not only in GitHub anymore.
The "Documentation" link on PyPI was pointing to README, but we now have the full docs.
=> Adapt the README for PyPI

kopf/structs/diffs.py, kopf/structs/lastseen.py, tests/diffs/test_diff.py, tests/diffs/test_reduction.py, tests/diffs/test_resolving.py
> Issue : #13 
Diffs are used in the `kopf.on.update` handlers, and then in the per-field handlers. They are very minimalistic and very simple structures, easy to test.
=> Test diffs calculation and manipulation

tests/diffs/test_diff.py
Signed-off-by: Melchior Fracas <melchior.fracas@zalando.de>
> Issue : #13  (only if appropriate)
This Commit aims at adding tests which describe likely usages of the diff library.
See [discussion](https://github.com/zalando-incubator/kopf/pull/40#discussion_r278212989).
=> adding documentation tests to test_diff

kopf/reactor/queueing.py
> Issue : #42 
With this change, if the queue contains a batch of events, react only to the latest one — to follow the "eventual consistency" principle of Kubernetes.
The batch is time-framed to 0.1s, so that it is fast enough for all normal cases when only one event arrives, but slow enough for the initial object listing when multiple events arrive. 
Still, some minimal time-frame is needed, as the streaming and parsing of the events inside of the kubernetes library is not immediate.
=> Handle only the latest event with the most up to date state

docs/deployment-rbac.yaml, docs/deployment.rst
> Issue : #12, #49 
The docs were missing the cluster-vs-namespaced object separation.
And there were no "GET" permission on the peering object by its name. Now, it is added to address our incident (see #49 background).
These docs will be later affected by #36.
=> Fix the docs for the RBAC examples, and add "get" permission on peering

kopf/reactor/handling.py, kopf/reactor/invocation.py, tests/invocations/test_callbacks.py
The handlers, both sync and async, so as the lifecycle callbacks are called via the same protocol. This PR extracts this callback invocation protocol into a separate module (to reduce the complexity of `kopf.reactor.handling`), and add some tests for the invocation protocol. 
> Issue : #13 
The "invocation protocol" means that all expected kwargs (a dozen of them) will be indeed passed to the handlers, and that none of them will ever be accidentally "lost", thus breaking the operators — the framework's public promise (https://kopf.readthedocs.io/en/latest/handlers/#arguments).
In addition, sync & async callbacks are tested to behave as promised in the documentation (https://kopf.readthedocs.io/en/latest/async/): 
* The async callbacks are expected to be called in the same asyncio loop, …
=> Test the callback invocation protocol

kopf/__init__.py, kopf/structs/hierarchies.py, tests/hierarchies/conftest.py, tests/hierarchies/test_labelling.py, tests/hierarchies/test_name_harmonizing.py, tests/hierarchies/test_namespace_adjusting.py, tests/hierarchies/test_owner_referencing.py
These tests "freeze" the public interface of the library regarding the hierarchy management — to prevent accidental regressions.
> Issue : #13 
Few fixes are added just to pass the tests. They slightly extend the behavior: instead of purely `list` & `tuple` classes, any iterables are accepted.
Mostly for the purpose of testing, but also as a possibility, the public interface was also extended by the namespace adjustments (move objects to the requested namespace if it is not yet set) and name harmonizing (setting either the names or the name prefixes for the objects if they are not yet set).
These two additions are directly used in the object "adoption" (i.e. assignment as a children of another parent object, and aligning all of its properties: labels, names, namespaces, etc).
=> Tests for object hierarchies

kopf/reactor/lifecycles.py, tests/lifecycles/conftest.py, tests/lifecycles/test_global_defaults.py, tests/lifecycles/test_handler_selection.py, tests/lifecycles/test_real_invocation.py
> Issue : #13 
Test and fix the lifecycle callbacks. They are used to select the handlers to be executed on each handling cycle.
By default, `asap` is used, and it was slightly broken due to hard-coded structure of the `status` field (the change was done before importing to GitHub, but not reflected in this line). Now, it uses the provided function to get the retry count — from the same module where this value is set/updated.
=> Test the lifecycles

kopf/reactor/queueing.py, kopf/reactor/watching.py
> Issue : #13
It is done as a preparation for the tests of watch-streaming & event multiplexing tests — just to make both change-sets easier to review.
This extraction is same-for-same, no changes in the logic. Only the code cohesion is adjusted: the watch-calls are now next to the streaming/iterating routines, away from queueing part.
=> Extract the watching logic into a separate module

docs/deployment-rbac.yaml, docs/deployment.rst, docs/peering.rst, kopf/reactor/peering.py, kopf/reactor/queueing.py, peering.yaml
> Issue : #32, related #31, #17
For the purpose of strict namespace isolation of the operators, the peering objects must be cluster- or namespace-scoped (previously: always cluster-scoped). 
For this, split the old cluster-wide `KopfPeering` resource into the new `ClusterKopfPeering` & namespaced `KopfPeering`, and use one of them depending on the `--namespace` option.
The testing of peering is performed manually — it works. More tests will be added when the whole peering subsystem will be covered with tests (as part of #13).
Docs preview:
* https://kopf.readthedocs.io/en/peering-scopes/peering/
* https://kopf.readthedocs.io/en/peering-scopes/deployment/#rbac
See also: #37 for the namespace isolation of the listing/watching API calls.
TODO:
=> Peering scopes

kopf/structs/lastseen.py
> Issue : #64
Ignore the incremental changes of `metadata.generation`, which automatically happen on any PATCH operation.
There are no unit-tests on this module yet, to be done in #13.
=> Ignore metadata.generation in last-seen state checks and diffs

kopf/reactor/peering.py
> Issue : #32, related #31, #17
Introduced in #36 (merged few minutes ago): When the cluster is totally empty and does not have a CRD for KopfPeering (not only the objects), the legacy validation failed. 
Now, it will also fall back to the standalone mode.
=> Fix the case when KopfPeering does not exist at all

docs/index.rst, docs/testing.rst, kopf/testing/__init__.py, kopf/testing/runner.py, tests/testing/test_runner.py
> Issue : #52 
Provide the basic tools for the operator developers to test their Kopf-based operators.
This feature will be used also to run end2end tests in the following PRs (e.g. #54).
=> Provide the basic testing tools for the operator developers

kopf/structs/progress.py, requirements.txt, tests/test_progress.py
> Issue : #13 
Only the tests and few little edge-case fixes for the routines handling the progress storage.
The progress storage is used by the framework to keep the status of the handlers, their errors or delays, and the multi-handler processing in general.
The progress struct itself is already documented in the `kopf.structs.progress` docstring with a sample, see here: https://github.com/zalando-incubator/kopf/blob/master/kopf/structs/progress.py
=> Test the routines for the progress status storage

.travis.yml
> Issue : #13
This PR just enables the Python 3.8 (dev) builds, but allows them to fail. 
This is mostly to see if there any upcoming issues before the release of Python 3.8 (scheduled to ~Oct'2019).
=> Enable Python 3.8 (dev) to preview the upcoming issues

CONTRIBUTING.md, docs/contributing.rst, docs/index.rst
> Issue : #12 
Move the code contribution guidelines from the top-level Markdown file to the documentation, and expand it with details.
In addition, some naming issues are fixed in `CONTRIBUTING.md` (capitalised "Kopf" name).
=> Expand the code contribution conventions & requirements in the docs

kopf/reactor/handling.py, kopf/structs/diffs.py, tests/diffs/test_resolving.py
> Issue : #13
As accidentally detected during #69 — this fixes a little issue with `KeyError` raised when the field is removed from the object, and a field-handler is called for that event, and fails to "resolve" the old/new value for the field-handler (i.e. a subset of a bigger diff-object), as the field is not in one of those per-object old/new structs.
=> Fix the detection of field deletion in diffs

docs/deployment-depl.yaml
> Issue: #12 
Use the stable Kubernetes workloads API version, see https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
=> Docs: use stable Workloads API (apps/v1)

kopf/reactor/invocation.py, tests/invocations/test_callbacks.py
> Issue : #79 
Add the missing kwargs to the handler functions for the commonly used metadata fields. Specifically, `namespace` was mentioned in the docs, but absent in the code.
=> Add few missing kwargs to the handler invocation (used in docs)

.travis.yml, kopf/k8s/events.py, tests/k8s/test_events.py, tools/minikube-for-travis.sh
> Issue : #76 
Starting from GKE 1.12 (Google Kubernetes Engine), the legacy APIs are disabled by default — `disable-legacy-endpoints=true` is added on the cluster creation. [Official doc](https://cloud.google.com/kubernetes-engine/docs/how-to/protecting-cluster-metadata#disable-legacy-apis).
As such, events of `v1beta1` are not accessible, and Kopf fails on the simple examples (see #76). `v1` events should be used instead.
This PR switches to the `v1` events. And v1beta1 are now disabled for Minikube, so it will fails if accidentally used. Also, it adds the unit-tests that were absent since #71 .
Beside the tests, I have manually tested the Kopf example operator to run in GKE — now, it works (before the fix, it was failing on the event posting).
=> Use the core v1 API instead of v1beta1, for GKE>=1.12 compatibility

kopf/on.py, kopf/reactor/registries.py, tests/registries/test_decorators.py, tests/registries/test_handler_matching.py, tests/registries/test_id_detection.py
> Issue : #13 
The `FIELD` pseudo-cause was introduced as an easy way to mark the per-field handlers (`@kopf.on.field`), and then to select them on the event handling. The field handlers were handled separately, after all the object handlers.
Over time, this pseudo-cause was merged into the overall handling routine, and has become a problem: it prevents further refactoring (of event/cause detection and handling), which in turn is needed for the test coverage.
----
This PR is a set of changes extracted from a bigger branch for the ease of code review (one small part at a time). It does NOT change the behaviour of the framework or of any handlers; it just changes the internal implementation of it:
* No more `FIELD` pseudo-causes in the code.
* The catch-all handlers (`event==None`) with …
=> Refactor the FIELD pseudo-cause into the catch-all events and a field filter

kopf/on.py, kopf/reactor/causation.py, kopf/reactor/handling.py, kopf/reactor/registries.py, kopf/structs/finalizers.py, kopf/structs/lastseen.py, tests/basic-structs/test_cause.py, tests/causation/test_detection.py, tests/conftest.py, tests/handling/conftest.py, tests/handling/test_delays.py, tests/handling/test_errors.py, tests/handling/test_freezing.py, tests/handling/test_handling.py, tests/handling/test_multistep.py, tests/handling/test_timeouts.py, tests/lifecycles/test_real_invocation.py, tests/registries/test_decorators.py
> Issue: #13
**Briefly:** add tests for the core part of Kopf: event handling.
This covers the whole chain of handling: from the raw streaming/watching event reception and down to the handler function invocation.
Two sections are explicitly separated from the previous handling routine — to make them testable:
* Cause detection (`kopf.reactor.causation`) — for converting all possible event type and object fields combinations to the cause objects.
* Cause handling (`kopf.reactor.handling`) — for actual handler invocation, logging, exception handling, status/progress storage, patching, sleeping, etc.
As part of this PR, a refactoring is made to split these two parts into separate modules, so that become testable.
=> Test the event handling; and separate the cause detection from handling

kopf/k8s/events.py, tests/k8s/conftest.py, tests/k8s/test_events.py
> Issue : #87 
Handle the case when Kopf fails to post a Kubernetes event (for logging), and by doing so interrupts the handling cycle. The events are auxiliary by their nature, not mandatory. Their errors should not break the framework's or operator's behaviour. Yet they must be noticed (e.g. in logs).
With this PR, the event posting is changed:
* If any API error happens during posting an event, a warning is logged, but the operator continues to handle the resources. The event info and the error are both put to the logs for later investigation.
* The messages are cut to 1024 characters, keeping the starting and ending parts, and putting an infix in the middle. At least something will be posted, which is better than nothing at all.
By occasion also move the shared parts to conftest, as …
=> Suppress errors in event posting, and prevent them when possible

docs/handlers.rst, examples/08-events/README.md, examples/08-events/example.py, kopf/on.py, kopf/reactor/handling.py, kopf/reactor/invocation.py, kopf/reactor/registries.py, kopf/structs/status.py, tests/cli/test_preloading.py, tests/handling/conftest.py, tests/handling/test_cause_handling.py, tests/handling/test_event_handling.py, tests/registries/test_decorators.py, tests/registries/test_global_registry.py, tests/registries/test_handler_matching.py, tests/registries/test_id_detection.py, tests/registries/test_registering.py, tests/test_progress.py
> Issue: closes #30
Add the simplistic event-handlers for spying on the low-level events of other resources,
not belonging to the operator (and not storing any status fields or finalizers or so).
The syntax is:
```python
import kopf
@kopf.on.event('zalando.org', 'v1', 'kopfexamples')
def event_fn(event, **kwargs):
pass
```
The difference from the regular handlers is documented in the `docs/handlers.rst` (see the changed files). Briefly:
* No state storage on the objects.
* No annotations or finalizers added to the objects.
* No k8s-events posted for the activity (only the stdout/stderr logs).
Altogether, this means "silent" — the objects do not know they are being watched & handled (i.e. spied).
Checklist:
=> Add the silent spy-handlers for the raw events, no persistence

docs/continuity.rst, docs/idempotence.rst, docs/index.rst, docs/troubleshooting.rst
> Issue : closes #75, closes #12
Add some pages for the maintenance of the Kopf-based operators, describing their behaviour on downtime, on restarts, how they keep the persistence.
Add the troubleshooting page for some unexpected behaviour, to make it clear (e.g. #75).
_A new section was needed, as this kind of information does not fit to Tutorial, Features, About Kopf, and not even to the Developers Manual (which is about developing Kopf itself, not the Kopf-based operators)._
Preview:
* https://kopf-nolars-fork.readthedocs.io/en/docs-maintenance/continuity.html
* https://kopf-nolars-fork.readthedocs.io/en/docs-maintenance/idempotence.html
* https://kopf-nolars-fork.readthedocs.io/en/docs-maintenance/troubleshooting.html
=> Document the operator maintenance

kopf/structs/finalizers.py, tests/test_finalizers.py
> Issue : #13 
Add tests for the finalizers: appending, removing, checking.
Also change the finalizer to a FQDN string — as once I hit the issue that the finalizer cannot be an arbitrary string (e.g. when assigning it to a pod in Minikube; but it works with custom resources though).
But keep the legacy finalizer (just a string, not FQDN) if it is assigned to the existing resource — for checking and for removing.
=> Test for finalizers

docs/deployment-rbac.yaml
> Issue : #76, follow up for #81
In #81, new events API was used, but the documentation was not updated with the proper RBAC file. 
It did not affect the behaviour of the framework or of operators, but can cause confusion with the new users.
=> Add the new-style events (of v1 core API) to the RBAC docs

kopf/reactor/causation.py, kopf/reactor/handling.py, tests/e2e/test_examples.py, tests/handling/test_cause_handling.py, tests/handling/test_delays.py, tests/handling/test_errors.py, tests/handling/test_event_handling.py, tests/handling/test_multistep.py, tests/handling/test_no_handlers.py, tests/handling/test_timeouts.py
> Issue : #60
Currently, if there are no handlers, the handling attempt is anyway done, and the messages are logged that all handlers (zero out of zero) have succeeded.
With this PR, Kopf does not even attempt doing the handling cycle, if there are no handlers for the current event/cause. This also eliminates the unnecessary logging for fake handling cycles.
This PR is part of a chain leading to the resuming handlers on operator restarts: #103 -> #104 -> #105.
For simplicity in the future, a little refactoring is also performed: all causes are grouped into the internal and user-facing causes.
Also, the handling stack is now one call shorter (the all-purpose `execute()` is bypassed):
* Now:`custom_object_handler→handle_cause→_execute→call_handler`
* Was: …
=> Skip handling & logging when there are no handlers

kopf/structs/lastseen.py, kopf/test_lastseen.py
> Issue : #13 
Add tests for last-seen state (calculation and comparison).
The last seen state is used to detect the causes when something was changed (and what specifically), or to detect of the object is completely new (no previous seen state).
Partially, this is tested in the causation tests (indirectly). But there, it tests for how the states & diffs are used, without testing the details on the field level, and not all functions are fully tested.
The diff calculation (between old & new states) is left aside, as there are separate tests for it in `/tests/diffs/`.
=> Tests for last-seen state calculation and comparison

kopf/reactor/handling.py, tests/handling/conftest.py, tests/handling/test_cause_handling.py, tests/handling/test_cause_logging.py
> Issue : caused by #13 + #82
Log diffs during the handling cycles if there are detected diffs — usually on the `@kopf.on.update` handlers.
Since the recent unification of handling routines (#82), the logs were changed to the event dumps, and the update-diffs dumps were removed. 
Now, they can be seen (e.g. for debugging), in addition to the event dumps.
=> Log diffs when present

docs/handlers.rst, kopf/k8s/watching.py, kopf/on.py, kopf/reactor/causation.py, kopf/reactor/registries.py, tests/basic-structs/test_cause.py, tests/basic-structs/test_handler.py, tests/handling/conftest.py, tests/handling/test_delays.py, tests/handling/test_errors.py, tests/handling/test_multistep.py, tests/handling/test_timeouts.py, tests/reactor/conftest.py, tests/reactor/test_queueing.py, tests/registries/test_handler_matching.py
> Issue : closes #60, replaces #96 
Add the handlers for "resuming" (recalling? remembering?) an object in the operator:
```python
@kopf.on.resume('zalando.org', 'v1', 'kopfexamples')
def on_resume(**kwargs): pass
```
This complements the existing handlers for creation/update/deletion cases, and is injected into the handling cycle when one of the mentioned cases is detected (and handled normally), but strictly when the operator has started/restarted, and found that the object existed beforehand.
Which implies that if the object was created during the operator downtime, both `@kopf.on.create` **AND** `@kopf.on.resume` handlers will be called. Similarly, of the object was changed during the operator downtime, both `@kopf.on.update` **AND** `@kopf.on.resume` will be called (and both will get …
=> Add "resuming" handlers for resources (as co-handlers)

docs/deployment-rbac.yaml, kopf/k8s/fetching.py, tests/k8s/test_list_objs.py, tests/k8s/test_make_list_fn.py, tests/k8s/test_read_crd.py, tests/k8s/test_read_obj.py
> Issue : #12, #13, originally mentioned in #49 comments
Add the missing RBAC permissions for legacy CRD scanning in the documentation (deployment patterns, RBAC section).
Since CRD scanning is a cluster-scoped operation, and cluster-scoped RBAC is not always possible, make so that the "403 permission denied" response for CRDs is treated as the absence of CRD. It is currently only used for legacy peering CRD, and nothing else.
As part of that, in tests, also check for other typical statuses for all get/list API operations — via parametrization.
_PS: The feature was introduced in the automatic peering/standalone mode discovery (#33 #38)._
=> RBAC for automatic legacy peering detection

kopf/__init__.py, kopf/clients/events.py, kopf/engines/posting.py, kopf/events.py, kopf/reactor/handling.py, kopf/reactor/queueing.py, tests/handling/test_cause_handling.py, tests/handling/test_cause_logging.py, tests/handling/test_delays.py, tests/handling/test_errors.py, tests/handling/test_event_handling.py, tests/handling/test_freezing.py, tests/handling/test_multistep.py, tests/handling/test_no_handlers.py, tests/handling/test_timeouts.py, tests/posting/test_poster.py
> Issue : closes #111, prepares #117 
In #109, a lot of performance improvements were introduced to make all API calls asynchronous. One of them were the event-posting API calls, which are kind of logging for custom resource handling routines. However, there was a conceptual unresolvable issue:
Event-posting calls like `kopf.event()`, `kopf.info()`, so on — are synchronous functions. When called from an asynchronous coroutines (all of the Kopf internals), there is no way how the flow control can be returned to the asyncio event loop, as it requires `await`, which is a syntax error for sync-functions. The actual event-posting functions via API calls, however, must be async (explicitly or via thread executors), not sync and blocking. 
This problem is nicely described, for example, in this …
=> Post k8s-events in the background

docs/continuity.rst, docs/handlers.rst, kopf/on.py, kopf/reactor/causation.py, kopf/reactor/handling.py, kopf/reactor/registries.py, tests/causation/test_detection.py, tests/e2e/test_examples.py, tests/handling/conftest.py, tests/handling/test_cause_handling.py, tests/handling/test_delays.py, tests/registries/test_decorators.py
> Issue : #24
Adding finalizers to resources means that resources cannot be deleted if the operator is not running. This PR makes sure that finalizers are added only when strictly necessary, i.e. when there are mandatory deletion handlers. If there are no deletion handlers registered, then no finalizers will be added, same if a deletion handler is marked as optional.
- Documentation / non-code
_List of tasks you will do to complete the PR_
=> Optional finalizers

docs/errors.rst
> Issue: #12 
Correcting a small typo in errors documentation page
- Documentation / non-code
None
=> Correcting Typo in errors.rst

docs/deployment-depl.yaml, docs/walkthrough/creation.rst, docs/walkthrough/deletion.rst, docs/walkthrough/updates.rst, examples/02-children/example.py, kopf/reactor/handling.py, kopf/structs/diffs.py, tests/cli/test_logging.py, tests/handling/test_delays.py
> Issue : #13, #115, #116 
Travis & pytest show some amount of warnings on the deprecated usage of some Python-related modules/functions.
This PR fixes them.
It affects nothing except for the purity of the output — both in tests and at runtime.
=> Cleanup deprecated things and fix the docs

examples/09-testing/test_example_09.py, tests/handling/test_cause_handling.py
> Issue : #24
Few cross-PR bugs were introduced to the tests (and tests only):
#118 added a new test, and it was broken with the modified master. The merge, however, had no conflicts. The framework's code is not broken and functions properly, as expected. It is only one test.
#126 added a new e2e test, which expected the deletion logs, which never appeared, as they were removed in #118 (no more deletion events if there are no deletion handlers).
=> Fix the newly added test with old checks

kopf/utilities/loaders.py
Add current dir to sys.path prior to imports
> Issue : closes #92 
> Origin: closes #93 (suggestions added and conflicts resolved; original author: @trondhindenes)
Fixes the bug where modules weren't importable from current path since `current dir` was missing from `sys.path` (where modules are resolved from)
=> Add file's dir to sys.path

kopf/reactor/causation.py, kopf/reactor/handling.py, kopf/reactor/registries.py, kopf/structs/dicts.py, kopf/structs/lastseen.py, tests/causation/test_detection.py, tests/diffs-n-dicts/test_cherrypicking.py, tests/diffs-n-dicts/test_ensuring.py, tests/handling/conftest.py, tests/handling/test_cause_logging.py, tests/test_lastseen.py
> Issue : closes #129, prepares #119, regression of #64, closes #130 (supersedes it).
Kopf remembers the last-handled state in the annotations. It is then used to detect if the object was handled previous and should be handled now, and also whether it is a CREATE or UPDATE cause (affects the selected handlers).
**`.status`:** Currently, the `.status` stenza is fully included in the last-handle state, except for Kopf's own structures (`.status.kopf`). According to the K8s conventions, status should be generally ignored when triggering the events, as all other controllers and operators can store any arbitrary information there. See also #119.
**`.metadata`:** Similarly for `.metadata` — new fields appear over time. For example, now it is `.metadata.deletionGracePeriodSeconds` that was added …
=> Purge status & metadata from the last-handled state

setup.py
> Issue : #134
Restrict `kubernetes` client library to `<10.0.0`, as 10.0.0 is broken (both for Kopf and for an isolated example).
A hotfix version [kopf==0.17.post1](https://github.com/zalando-incubator/kopf/releases/tag/0.17.post1) was released to hot-fix this issue for regular use of Kopf via `pip install kopf` (0.17 is the latest released version to the moment).
But this same restriction must be in the master branch before the next version is released (i.e. for 0.18).
=> Restrict kubernetes client library to version 9.x.x

.gitignore, docs/peering.rst, kopf/engines/peering.py
> Issue : #51
When two operators runs with the same priority, both will handle the same request. This PR adds the possibility to freeze all events with the same priority, as mentioned in #51 and print a warning error.
=> Freeze all operators with same priority and warn

kopf/__init__.py, kopf/config.py, kopf/engines/logging.py, kopf/engines/posting.py, kopf/reactor/handling.py, tests/conftest.py, tests/handling/test_cause_logging.py, tests/handling/test_freezing.py, tests/posting/test_log2k8s.py, tests/posting/test_selfdestruction.py
> Issue : #136 
_As a logical continuation of #125:_
Kopf is not a K8s API client library. Therefore, it should not provide any means of talking to the K8s API. The operators developers should use the K8s API client libraries of their choice. This also applies to K8s-event posting.
However, Kopf provides few routines for k8s-event posting: `kopf.event()`, `kopf.info()`, `kopf.warn()`, `kopf.exception()`. This is highly useful for logging not only to the logs (stdout/stderr), but also to K8s itself.
To deal with this dilemma, this PR changes the way how Kopf deals with this specific field — logging to k8s events:
Instead of providing the methods to explicitly post everything in addition to regular logging (thus duplicating the messages and code), everything logged to the per-object logger …
=> Log to k8s events

.codecov.yml, .travis.yml, README.md, pytest.ini, requirements.txt, tests/conftest.py, tests/e2e/conftest.py
> Issue : closes #99, previously #13 
_(Playing with CodeCov and branches, need the real PR for this.)_
---
**Tools:**
Few tools are enabled for the same coverage measurements. More can be added over time — to compare and to use the benefits of all of them.
* CodeCov: https://codecov.io/gh/zalando-incubator/kopf (nice graphs, no if-branch coverage).
* Coveralls: https://coveralls.io/github/zalando-incubator/kopf (if-branch coverage, poor graphs).
---
**Historic measurements:**
The code coverage measurements for CodeCov were replayed for the whole git log — i.e. every commit — to render the graph nicely.
Coveralls does not date the coverage uploads to the commit timestamps (or it seems so), so it makes no sense to replay.
The ad-hoc script for replaying the history is here: …
=> Measure the code coverage and upload reports

kopf/clients/auth.py, kopf/clients/fetching.py, setup.py
Fix an issue with the operator dying in 10 seconds after starting — with `socket.timeout` and `requests.exceptions.ConnectionError` exceptions.
> Issues: #110 
Caused by the pykube's default of 10s for all requests, including the watch-requests (which are also `GET`). See  https://github.com/hjacobs/pykube/pull/32
Introduced to Kopf in #110. Specifically, the [timeouts were discussed](https://github.com/zalando-incubator/kopf/pull/110#discussion_r301153102) there, and converted from no-timeouts to default 10s. 
This PR reverts it back to no timeouts for all internal requests. This topic was also discussed in few other Kopf's PRs — it should work even on the slow clusters, even over the slow network connections (e.g. in IDEs over network).
And, in case the socket timeout will be revised or …
=> Disable socket timeouts for internal request, especially for watching

.travis.yml, pytest.ini
Disable coverage measurements by default. Enable explicitly for CI.
> Issue : #99 
In #72, coverage has been enabled by default for all runs. While this fine for CI runs, it was conflicting with the test runs in IDEs: coverage uses the same `set_trace()` calls as the PyCharm debugger.
In general, unless explicitly enabled, coverage is not needed in the IDEs, or even in the CLI runs.
Hence, disable it by default, and enable it for CI runs only.
- Configuration change
=> Turn of coverage by default; turn on for CI only

kopf/reactor/queueing.py, tests/conftest.py
_Part of an effort to make Kopf-based operators more stable and resilient._
> Issue: #142, partially replaces #143.
First of all, react to SIGINT/SIGTERM at all. Previously, the process was terminated on the OS level, but not via the intended reaction.
Second, when exiting for any reason — e.g. SIGINT/SIGTERM, or explicit cancellation, or any exception — do this as gracefully as possible. For this, first cancel the core ever-running tasks of the framework; give them some time to finish; then cancel all running tasks & sub-tasks if left; give it some time again; and only then actually exit.
Third, add a check for all tests on whether any pending tasks are left unattended (i.e. scheduled but not executed) — which is especially important for the e2e tests.
**There are no behaviour changes …
=> Gracefully terminate an operator on SIGINT/SIGTERM

kopf/reactor/queueing.py
> Issue: #142, introduced in #147 
Sadly so, in #147, an error sneaked into the code: 
`Event.set()` does not accept any arguments, but they are passed into a callback. The callback was originally implemented as a separate async-function, which took a list of tasks and cancelled all of them. Then, the callback was replaced to a flag-setting. But the argument with a list of tasks went unnoticed.
This only affects the operators on its termination stage (Ctrl+C or pod deletion/restarting), and does not affect the behaviour itself.
=> Fix the stop-flag setting: no arguments are expected

examples/09-testing/test_example_09.py, examples/10-builtins/test_example_10.py, kopf/testing/runner.py, tests/e2e/test_examples.py
_Part of an effort to make Kopf-based operators more stable and resilient._
> Issue : #13 #142 
E2E tests are flaky and unstable. This PR makes them more stable by:
* Running in a standalone mode (on the same minikube as other, probably failed tests — to prevent freezing for minutes).
* Limiting a time of termination of a background operator to 60s (and adding this feature).
* Using a dynamic pod name in the pod-involving e2e tests (otherwise, it hits "409 Conflict" — when the pod already exists in the same cluster (actual for the local runs)).
=> Improve the stability of e2e tests

kopf/__init__.py, kopf/cli.py, kopf/clients/fetching.py, kopf/clients/watching.py, kopf/reactor/queueing.py, kopf/reactor/running.py, tests/cli/conftest.py, tests/cli/test_help.py
_A preparation for switch to aiohttp and full-async._
> Issue : #142 
In order to make the coming PRs easier to read with their diffs, this is a preparatory PR with no behaviour changes, no code modified, but only with the code moved across the modules.
As the code grows, some modules need to be split:
* `kopf.reactor.queueing` is split into:
* `kopf.reactor.running` for asyncio task management (starting and orchestration).
* `kopf.reactor.queueing` for watch-event queueing and multiplexing only.
Other functions have to be moved for cohesion to their related functions:
* `watch_objs` moved from `kopf.clients.fetching` to `kopf.clients.watching` (with the intention of reimplementing the watching & streaming).
_The behaviour is NOT changed in any way._
=> Move and split the modules (no code/logic changes)

docs/embedding.rst, docs/index.rst, kopf/__init__.py, kopf/reactor/running.py
Make operator termination even more graceful (resource-cleanable), the task orchestration — async, and the operator core — embeddable (and officially documented).
> Issue : #142.
Previously in #147, there was an attempt to rework the asyncio task management with the "should-stop" event and asyncio task cancellations. It made the operator to react to the existing signals, but still had some problems with proper cleanups.
Specifically, when a `aiohttp.ClientSession` is added (a PR based on this one — to be created), there is no place to properly create it and close it, since all the tasks are orchestrated in a synchronous function.
This led to few issues with some `aiohttp` connections not being closed properly, issuing the warnings/prints on the process exiting (and a lot of them in …
=> Refactor runtime to full async/await; make officially embeddable

.codecov.yml
> Issues: #99 
Despite using the "default" behaviour (post if new, update if existing), CodeCov continues to re-create the comments with the coverage, spamming the email.
This PR disables the CodeCov's comments completely.
PS: A similar issue existed for numpy in 2018: `https://github.com/numpy/numpy/issues/11984`
=> Disable CodeCov's PR spamming

kopf/clients/events.py, kopf/engines/logging.py, kopf/structs/hierarchies.py
K8s-events cannot be posted cluster-scoped (?), and attached to cluster-scoped resources via API. However, we post them to the current namespace — so that they are not lost completely.
> Issue : #164
See #164 for details. 
Brief summary: K8s events are namespaced, there are no cluster-scoped events. Also, k8s events can refer to an object via spec.involvedObject of type ObjectReference. This structure contains namespace field, to refer to the involved object's namespace (also, name, uid, etc).
I could not find a way to post namespaced events for cluster-scoped resources. It always fails with namespace mismatch (regardless of which library is used). Event via `curl` — see the issue comments.
So, we post the k8s-events to the current namespace, so that they are available via `kubectl get …
=> Post events for cluster-scoped objects to current namespace

docs/errors.rst, docs/idempotence.rst, docs/walkthrough/creation.rst, docs/walkthrough/deletion.rst, docs/walkthrough/updates.rst, examples/03-exceptions/example.py, kopf/__init__.py, kopf/reactor/handling.py, tests/handling/test_delays.py, tests/handling/test_errors.py, tests/handling/test_timeouts.py
Do not print stacktraces of internal temporary/permanent errors, just log the message.
> Issue : #16
The internal temporary and permanent errors are special exceptions to control the framework's flow of handler execution: either to retry it, or to stop trying — regardless of the global mode on arbitrary error handling _(in the assumption that `retry_on_error` will be exposed to the users some day)_.
They are supposed to already contain the information needed to identify the cause of the problem. Stacktraces are not needed (they are needed only for the unexpected errors with unclear origin).
Instead, stacktraces of these special errors make it difficult to identify when an actual unexpected errors happens (by visually or automatically looking for stacktraces in the logs).
Therefore, the …
=> Log the framework-provided exceptions with no stacktraces

kopf/clients/patching.py, tests/k8s/test_patching.py, tests/k8s/test_read_obj.py
Ignore errors when patching an object that was removed too quickly, during the handling cycle or inside of the handlers.
> Issue : #139
If a handler deletes the object being handled, Kopf will try to patch its status after the handler as usually, and will fail, since the object does not exist anymore.
The same happens if the object is deleted too quickly, while the handler is running. 
Previously, this was prevented by always having a finalizer before any handling. Since #24, the finalizer is added only when there are non-optional delete handlers, and skipped otherwise. So, it is now possible that the object is deleted while we handling it.
=> Ignore "404 Not Found" when patching after deletion during handling

kopf/engines/peering.py, kopf/engines/sleeping.py, kopf/reactor/handling.py, kopf/reactor/queueing.py, tests/handling/conftest.py, tests/handling/test_cause_handling.py, tests/handling/test_cause_logging.py, tests/handling/test_delays.py, tests/handling/test_errors.py, tests/handling/test_event_handling.py, tests/handling/test_freezing.py, tests/handling/test_multistep.py, tests/handling/test_no_handlers.py, tests/handling/test_timeouts.py, tests/reactor/conftest.py, tests/reactor/test_queueing.py, tests/test_sleeping.py
Wake up and react immediately when new watch-events arrive while operator is sleeping until the next delayed/postponed handler.
> Issue : #161, indirectly #142 
Previously, Kopf used `asyncio.sleep()` for shortest sleep duration until the next postponed handler. If new events arrived for that object — e.g. it was changed or deleted — the sleep continued unconditionally.
With this PR, the sleep until the next postponed handler will be interrupted as soon as a new event arrives (i.e. the object's event queue is replenished). Kopf will reconsider the next steps based on the new object's state, and either process the new state (e.g. finish handling the deleted object), or continue sleeping for the remaining time.
Both intended and remaining time are logged. For example:
```
[2019-08-02 …
```
=> Interrupt the sleep for the delayed handlers on new changes

kopf/reactor/running.py
> Issue : #142 #156 
Introduced implicitly in #156: When the operator was made embeddable, the defaults were not removed from the function signatures. 
Normally, they were overridden by the CLI defaults and set to `None`. But not when the function was called as `kopf.operator()`.
As a result, the embedded operator (kopf==0.21rc1) failed on startup due to a peering error (because the name was explicitly set, as if `--peering=default` was passed to CLI).
=> Remove the default peering for embeddable operator

kopf/cli.py
add `--version` command to print the version of kopf
> Issue : #172
=> Add --version command to print the version of kopf

kopf/reactor/causation.py, kopf/reactor/handling.py, kopf/structs/lastseen.py, kopf/structs/status.py, tests/basic-structs/test_cause.py, tests/causation/test_detection.py, tests/handling/conftest.py, tests/handling/test_delays.py, tests/handling/test_errors.py, tests/handling/test_multistep.py, tests/handling/test_timeouts.py, tests/test_lastseen.py, tests/test_progress.py
Keep track of which state was handled by which handler, and re-execute it if the state is changed during the handling cycle.
> Issue : replays #9, indirectly #161 and #150
In #9, there was an attempt to make the handler's status persistent. As a side-effect, it also could detect the state changes during the handling cycle. The persistent progress was not needed or not much useful. However, the change detection is needed again. This PR partially replays the same solution.
Currently, if an object is changed during the long handling cycle (which can include multiple handlers and multiple retries — i.e. for hours sometimes), these changes will not be noticed in some handlers. The "last-seen" state will be stored as it was at the moment of the _last_ handler, and only the changes relative to …
=> Ensure that all handlers get the latest state (eventually)

kopf/reactor/queueing.py, kopf/reactor/running.py
Make it clear what is the reason of operator exiting. 
> Issue : #178 
Add slightly more logs on the operator termination, to show which tasks are exiting, whether that happens normally or by exception or due to cancellation.
Show which signal was received — and do this on the INFO level of logging, to be visible even in non-verbose mode.
Before this PR (sometimes even with no "stop-flag" mentioned at all):
```
[2019-08-09 18:15:07,179] kopf.reactor.running [DEBUG   ] Stop-flag is raised. Operator is stopping.
[2019-08-09 18:15:07,216] kopf.reactor.running [DEBUG   ] Root tasks are stopped: finished normally; tasks left: set()
[2019-08-09 18:15:07,216] kopf.reactor.running [DEBUG   ] Hung tasks stopping is skipped: no tasks given.
```
After this PR:
```
[2019-08-09 18:14:20,780] …
```
=> Log verbosely on the operator termination reasons

kopf/reactor/causation.py, kopf/reactor/handling.py, kopf/structs/lastseen.py, kopf/structs/status.py, tests/basic-structs/test_cause.py, tests/causation/test_detection.py, tests/handling/conftest.py, tests/handling/test_delays.py, tests/handling/test_errors.py, tests/handling/test_multistep.py, tests/handling/test_timeouts.py, tests/test_lastseen.py, tests/test_progress.py
> Reverts zalando-incubator/kopf#163, affects #150 
This feature (per-handler reconciliation) has introduced inconsistent behaviour with field-handlers and sub-handlers.
Specifically, it causes the field-handlers and sub-handlers with side-effects to be executed again and again if the spec/status fields of interest are changed during the multi-step handling cycle (when it is not fast enough — e.g. due to errors & retries) — because the digest changes globally for the object in that case. And it only stabilises when there are not external changes of the fields during the full handling cycle (if it is fast enough).
Conceptually caused by misalignment of per-object and per-handling-cycle state persistence (last-handled-state/diff/old/new), and per-handler digest remembering and comparison — …
=> Revert "Ensure that all handlers get the latest state (eventually)"

docs/embedding.rst, examples/12-embedded/README.md, examples/12-embedded/example.py, examples/12-embedded/test_nothing.py, kopf/reactor/running.py
Add stop/ready flags to the operator coroutines, and add an example for the embedded operator, which uses these flags.
> Issue : #184, follow-up for #156.
The stop-flag is used to signal the operator (from the outside caller) that it should terminate gracefully.
The ready-flag is used to signal the outside caller (from the operator) that the operator has initialised and is ready to work.
This bi-directional communication slightly simplifies the orchestration of the operators when they are embedded into arbitrary applications (i.e. not called via `kopf run`). This could be also done by cancelling the task of the operator, but that would require few extra lines to operate it (checking for the cross-thread flag and finishing the asyncio task), which are already present inside of the operator …
=> Add an example for embedded operator (and stop/ready flags)

kopf/config.py, kopf/engines/logging.py, kopf/engines/posting.py, tests/posting/test_log2k8s.py, tests/posting/test_poster.py
Fix an issue with k8s-events posted for log messages despite the configured levels.
> Issue : fixes #188
Configured log levels was ignored in the connector of the `logging` facilities to the k8s-event posting engine, so all events were posted. The docs were written for the event-posting shortcuts, but this was not taken into account when the log-posting engine was added.
In addition, some extra checks are added to verify that the shortcuts actually obey the configured levels.
**Note** that the debug level messages are now filtered not by the K8s-posting handler `K8sPoster` — the minimum level is removed from there— but by its `filter()` method, based on the Kopf's configs. Which is generally equivalent, as it was previously filtered by level in `super().filter(record)`, which stands in …
=> Obey the configured levels when posting from `logging`

.travis.yml, tools/kubernetes-client.sh, tools/minikube-for-travis.sh
Replace the explicit Kubernetes versions in CI/CD with the "latest" aliases.
> Issue : #13
Previously, all Kubernetes versions were explicitly enumerated in the CI/CD config. We had to add new Kubernetes versions from time to time. Same for Minikube.
Now, the "latest" will be used for both. Extra versions versions to test still have to be listed explicitly  (to my knowledge, there is no "latest minus 1", "latest minus 2", or so).
Now, the Travis build looks like [this](https://travis-ci.org/nolar/kopf/builds/589950167):
=> Automatically test with the latest Kubernetes version

kopf/clients/fetching.py, kopf/clients/watching.py, tests/k8s/test_list_objs.py
Refactor clients-to-reactor communication to prepare for the overall type-hinting.
> Issue : #194 
Since the switch to pykube-ng (#71 #110), there was an [_abstraction leak_](https://en.wikipedia.org/wiki/Leaky_abstraction) in the list-fetching client wrapper: the `requests.Response` object was returned, thus exposing the internal implementation of a sibling module.
In this PR, the leak is removed, and the function now exposes only the data needed. It also takes the hacky data recovery (missing `apiVersion` & `kind` in the lists) from the Kopf's reactor into the client wrapper.
Having this in place will also simplify future switch to other HTTP clients, such as asyncio (see #176), as there is no such a specific response object in other implementations.
The function is intentionally …
=> Remove an abstraction leak of a Response object — for type-hinting

requirements.txt, tests/conftest.py
Adjust to the changed pytest-mock internal structure.
> Issue : #13 
In https://github.com/pytest-dev/pytest-mock/pull/160, on 2019-10-04 23:56 CEST, `pytest-mock=1.11.1` has changed its internal package-module structure. 
Kopf used its structure to replace one internal method to properly replace all mocks with async/awaitable mocks for total async transparency of the tests. After the change, Kopf's hack stopped having any effect.
_Yes, it is a bad practice, but this simplifies testing a lot, and there is no public interface for this._
This does not affect the Kopf itself, but only its tests (and therefore, all PRs that are (not) happening after this release).
This PR adjusts for the new structure of pytest-mock.
=> Fix the tests for the new pytest-mock package structure

kopf/on.py, kopf/reactor/causation.py, kopf/reactor/handling.py, kopf/reactor/invocation.py, kopf/reactor/registries.py, tests/basic-structs/test_cause.py, tests/basic-structs/test_handler.py, tests/causation/test_detection.py, tests/handling/conftest.py, tests/handling/test_cause_handling.py, tests/handling/test_cause_logging.py, tests/handling/test_delays.py, tests/handling/test_errors.py, tests/handling/test_event_handling.py, tests/handling/test_multistep.py, tests/handling/test_no_handlers.py, tests/handling/test_timeouts.py, tests/invocations/test_callbacks.py, tests/registries/test_decorators.py, tests/registries/test_handler_matching.py
Rename `cause.event` to `cause.reason` for clarity in terminology.
> Issue : #194
Originally, in the early stages of Kopf development, one of the cause's fields was named as `event`, when it actually represented a _reason_ of the reaction, or a _trigger_ for this reaction, or what is the detected kind of change.
Over time, this produced confusion, as there are already 2 _events_ present: the watching-events (streaming) and the `kind: Event` resources (logging) -- both are taken from the Kubernetes's terminology and cannot be avoided.
More on that, when the event-handlers were added, it created inconsistency for the `event` kwarg between the event-handlers and the cause-handlers: in the latter ones, it was a _reason_ of the change, while in the former ones, it was the raw event dict being …
=> Resolve a terminology conflict: cause.event → cause.reason

docs/handlers.rst, examples/08-events/README.md, kopf/on.py, kopf/reactor/causation.py, kopf/reactor/handling.py, kopf/reactor/invocation.py, kopf/reactor/registries.py, tests/basic-structs/test_cause.py, tests/causation/test_detection.py, tests/handling/conftest.py, tests/handling/test_cause_handling.py, tests/handling/test_freezing.py, tests/handling/test_no_handlers.py, tests/invocations/test_callbacks.py, tests/lifecycles/test_real_invocation.py, tests/registries/test_decorators.py, tests/registries/test_global_registry.py, tests/registries/test_handler_matching.py, tests/registries/test_id_detection.py, tests/registries/test_registering.py
Fix the terminology mess between the event-watching and state-changing causes & reactions.
> Issue : #194
Since the event-handlers were introduced, there was a terminology chaos in the framework. Specifically, the "event-handling" routines had different signatures than the "cause-handling" routines, despite doing exactly the same, in almost the same way. This became very obvious during the throughout type annotation in #200.
This PR changes the internal terminology both for causation and for handling of such different causes:
* All **ex-"event-handling"** routines were renamed to **"event-watching"** causes and routines -- as they trigger the reaction directly from the _event watching_ streams.
* The **ex-"cause-handling"** routines were renamed to **"state-changing"** causes and routines …
=> Resolve a terminology conflict: event-watching vs state-changing causes

docs/hierarchies.rst, docs/walkthrough/deletion.rst, docs/walkthrough/updates.rst, examples/02-children/example.py, examples/99-all-at-once/example.py, kopf/reactor/handling.py, kopf/reactor/invocation.py, kopf/toolkits/hierarchies.py, tests/hierarchies/test_contextual_owner.py
Assume the currently handled object as the default owner when adopting.
> Issue: closes #56
Simplify the usage of hierarchy management functions to make `owner` optional. If not specified, the currently handler object is assumed to be the owner, or the source of name prefix and namespace.
This is not done for labels, as I am not sure that `kopf.label(obj)` semantically implies the label transfer from the currently handled object. The labelling remains explicit.
=> Assume the current object as an implicit owner for hierarchies

kopf/toolkits/runner.py
Fix the mypy strict-mode error for context manager result.
> Issue : #200 
The new mypy 0.740 started to fail on `__exit__` result type (0.730 was fine with this):
```
$ mypy kopf --strict --pretty
kopf/toolkits/runner.py:79: error: "bool" is invalid as return type for "__exit__" that always returns False
def __exit__(
^
kopf/toolkits/runner.py:79: note: Use "typing_extensions.Literal[False]" as the return type or change it to "None"
kopf/toolkits/runner.py:79: note: If return type of "__exit__" implies that it may return True, the context manager may swallow exceptions
```
Sample CI: https://travis-ci.org/nolar/kopf/jobs/601269875
This PR does as recommended — annotate that it is literally `False`, not just any boolean.
=> Fix mypy's recommendations for `__exit__` results

kopf/reactor/handling.py, kopf/reactor/registries.py
Code refactoring (part 2 of 3): moving the code pieces around.
> Issue : preparation for #59 #187 #142
> Preceded: #209 (part 1/3)
This PR is purely **moving** of functions and methods — a part of the code refactoring needed to extend Kopf with the startup/cleanup/(re-)authentication background activities.
Historically, some code pieces were located in strange places. To minimise the size of the meaningful PR, the moves are extracted to this PR.
There are **NO** behavioral changes.
The public interfaces are kept **unmodified**. These are the internal changes only.
=> Refactoring [2/3]: code moves and extractions

kopf/__init__.py, kopf/on.py, kopf/reactor/handling.py, kopf/reactor/registries.py, kopf/toolkits/legacy_registries.py, tests/basic-structs/test_handler.py, tests/conftest.py, tests/registries/conftest.py, tests/registries/legacy/test_legacy_creation.py, tests/registries/legacy/test_legacy_decorators.py, tests/registries/legacy/test_legacy_default_registry.py, tests/registries/legacy/test_legacy_global_registry.py, tests/registries/legacy/test_legacy_handler_matching.py, tests/registries/legacy/test_legacy_id_detection.py, tests/registries/legacy/test_legacy_registering.py, tests/registries/legacy/test_legacy_requires_finalizer.py, tests/registries/test_creation.py, tests/registries/test_decorators.py, tests/registries/test_handler_matching.py, tests/registries/test_id_detection.py, tests/registries/test_operator_resources.py, tests/registries/test_registering.py
Code refactoring (part 3 of 3): bring proper OOP to registries.
> Issue : preparation for #59 #187 #142
> Preceded: #209 (part 1/3), #210 (part 2/3).
Bring registries to the proper OOP implementation, with inheritance and polymorphism. For histroic reasons and quick-prorotyping, they were initially implemented with different methods of the same class; now, it is done via different classes with one method overridden.
The ex-`GlobalRegistry` (now, the `OperatorRegistry`) is excluded from the registries hierarchy, since it shares 0 methods with other registies, and is implemented as a *composite* of specialised registries. The code now clearly annotates which registries are expected where — they are NOT interchangeable anymore.
The unit-tests for the old registry classes signatures are …
=> Refactoring [3/3]: proper OOP for registries

examples/03-exceptions/example.py, examples/99-all-at-once/example.py, kopf/cli.py, kopf/reactor/running.py, kopf/toolkits/runner.py, tests/e2e/conftest.py, tests/e2e/test_examples.py
> Issue : #13 #59 
Improve e2e tests to wait for the stop-words in the logs instead of just waiting for the time. It was quite common that the e2e tests do not fit into the empirically guessed timings, so the timings had to be increased far above what was normally needed — thus slowing the e2e tests.
This became even more important for the tests that contain the artificial delays, such as sleep, temporary errors with delays, or arbitrary exceptions with the default retry delay (even if mocked).
Now, they default delay is 10 seconds, but the tests continue as soon as they see the specially defined stop-words for each stage (creation, deletion; later: startup, cleanup).
In addition, the `KopfRunner` was improved to stop the background operator gracefully instead of the forced cancellation …
=> Speed up e2e tests and make them exiting gracefully

kopf/clients/classes.py, kopf/clients/fetching.py, kopf/clients/patching.py, kopf/clients/watching.py, kopf/engines/peering.py, kopf/reactor/running.py, tests/k8s/test_list_objs.py, tests/k8s/test_read_crd.py, tests/k8s/test_read_obj.py
> Issue : #142
The _client wrappers_ are used to isolate the framework's reactor from the specific HTTPS API calls needed to talk to Kubernetes, and from the ways of doing so. They provide a limited set of operations needed only, and no more than that (no general-purpose DSL for resource manipulation).
In this PR, all remaining synchronous client wrappers are converted to async coroutines, while they remain Pykube-based internally (`pykube-ng` is synchronous, as `requests` are synchronous).
This is needed both for the switch to aiohttp (e.g. #176), and for the re-authentication activities (few issues).
The synchronous calls are moved few levels down the stack, and put into the thread-pool executors. 
Previously, these calls were sync inside of the async event loop, so they were blocking. …
=> Convert client wrappers to coroutines, use thread pools for actual calls

kopf/reactor/running.py
When running kopf on Windows it fails due to NotImplementedError thrown by add_signal_handler method in asyncio
> Issue : #219 
In the asyncio docs it appears that the [add_signal_handler](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.add_signal_handler) method is only available in Unix which is why it throws a NotImplementedError when kopf is run on Windows.
This PR should fix Windows compatibility by catching NotImplementedError thrown by asyncio and continuing.
* Bug fix (non-breaking change which fixes an issue)
=> Fix Windows Compatibility

docs/errors.rst, examples/03-exceptions/example.py, kopf/__init__.py, kopf/on.py, kopf/reactor/handling.py, kopf/reactor/registries.py, tests/basic-structs/test_handler.py, tests/e2e/test_examples.py, tests/handling/conftest.py, tests/handling/test_retrying_limits.py, tests/registries/test_decorators.py
Extra keywords for the handlers to override the default exception-reacting behaviour (timeouts, retries, cool-down periods, arbitrary error interpretations).
> Issue : closes #16
With this PR, the error handling mode can be configured by handler (for arbitrary exceptions):
* Treat them as permanent: ``errors=kopf.ErrorsMode.PERMANENT``
* Treat them as temporary for N attempts: ``retries=3``
* Treat them as temporary for some time: ``timeout=60`` (exists already)
* Ignore them -- same as permanent, with better logging: ``errors=kopf.ErrorsMode.IGNORED``
The current and historic behaviour (the new default) is to treat all errors as temporary until the timeout is reached, or forever until the resource is deleted (if timeout is not set).
Also, a _cooldown_ period between retries can be …
=> Configure reactions to errors in the handlers, per-handler

docs/handlers.rst, kopf/on.py, kopf/reactor/causation.py, kopf/reactor/registries.py, tests/registries/test_decorators.py, tests/registries/test_resumes_mixed_in.py
Prevent resource/memory leaks in some edge cases with resuming+deletion handlers.
> Issue : #112 #230 
In #230, the resume handlers were fixed to be executed as regular resource-changing handlers, with multiple iterations if needed. Previously, they were executed only if they were _lucky_ to be the first and the only in the row, and if never retried due to errors.
---
**Problem:** 
This led to the resuming handlers executed even if the object was marked for deletion during the operator downtime/restart. Which, from one point of view, makes sense — since the object exists out there (only "marked" for deletion, but not actually deleted), so should be "resumed" in memory (despite it will be shut down and freed in few moments). 
But, from another point of view, leads to potential …
=> Skip resumes for deleted objects, unless explicitly marked for selection

docs/handlers.rst, kopf/reactor/causation.py, kopf/reactor/handling.py, kopf/reactor/invocation.py, kopf/structs/containers.py, tests/basic-structs/test_causes.py, tests/basic-structs/test_containers.py, tests/causation/test_detection.py, tests/handling/conftest.py, tests/hierarchies/test_contextual_owner.py, tests/invocations/test_callbacks.py, tests/lifecycles/test_real_invocation.py
> Issue : #112 
Since the per-resource in-memory runtime-only containers are already present in the core for internal purposes, it is easy to expose `memo` kwarg to the handlers, so that the can store arbitrary information or objects about resources.
Same as for the internal use, this should be the objects that are scoped to the operator life time, fully lost on restarts, i.e. not persistent. E.g. threads, tasks, locks, events. Maybe some regular scalars, if their meaning is also scoped to the operator process.
Example:
```python
import kopf
@kopf.on.create('zalando.org', 'v1', 'kopfexamples', cooldown=10)
def create_fn_1(memo, **kwargs):
print(f'{memo.xyz}')
@kopf.on.create('zalando.org', 'v1', 'kopfexamples')
def create_fn_2(memo, **kwargs):
memo.xyz = 100
```
In this example, …
=> Use `memo` for arbitrary per-resource payload during operator lifetime

examples/crd.yaml
Call it `kex` now.
> Issue : #12 
There is no big practical reason for such aliases.  Just for shorter typing and examples in the demos/slides.
Besides, it sounds fancy, and "keks" means "cake" in Russian.
- Configuration change
=> Add a couple of short and fancy aliases for KopfExample CRD

kopf/reactor/handling.py, kopf/reactor/states.py, kopf/structs/lastseen.py, tests/handling/test_cause_handling.py, tests/handling/test_cause_logging.py, tests/persistence/test_progress.py
Less patching, less logging when not needed.
> Issue : #1234 (only if appropriate)
Skip logging the empty diffs. They are useless. Especially on the resuming events, when the object is not changed actually. — As they are already skipped for the creation/deletion events, when the diff is a full-body vs. `None` diff.
Skip patching the body essence if it is the same as the one already stored on the object. This pollutes the logs with difficult-to-read JSON dumps, especially on the resuming events — when these patches and logs contain no useful information.
Skip purging the handler progress if there is no progress stored (e.g. for one-handler cases, when it succeeds immediately). This produced unnecessary API patches, and polluted the logs for no good reason.
These changes will reduce the …
=> Avoid meaningless logging of essence patches & empty diffs

kopf/utilities/piggybacking.py
> Issue : #242
`Authorization: Bearer` header was sent (without a token!) because there was a schema defined by default (`"Bearer"`), which should not be there (`None`).
This caused problems when Basic auth (username+password) was used — it could not co-exist with `Authorization: Bearer` header.
=> Fix an issue with mistakenly added Bearer auth in addition to Basic auth

kopf/clients/auth.py, tests/authentication/test_credentials.py, tests/authentication/test_tempfiles.py
> Issue : follow-up for #226, extra fix for #242 
In #226, custom authentication was added, with CA/SSL-cert/SSL-pkey accepted both as path and data — similar to how it is stored in the `~/.kube/config`.
However, data fields were ignored and not handled in any way.
This PR should fix this.
=> Support raw data for  SSL certs, pkeys, and CA

kopf/reactor/handling.py, tests/authentication/test_login.py, tests/persistence/test_outcomes.py
Fix GKE's authentication, which otherwise fails on pykube-ng's piggybacking.
> Issue : #226 
When GKE is used, `pykube-ng` fails to retrieve the credentials.  But `kubernetes` succeeds. — It was the initial intention to use whatever credentials are available.
However, due to an exception returned by one of the login handlers, the whole (re-) authentication activity fails.
```
[2019-11-19 21:20:13,014] kopf.reactor.activit [INFO    ] Initial authentication has been initiated.
[2019-11-19 21:20:13,019] kopf.activities.auth [DEBUG   ] Invoking handler 'login_via_pykube'.
[2019-11-19 21:20:13,090] kopf.activities.auth [DEBUG   ] Pykube is configured via kubeconfig file.
[2019-11-19 21:20:14,339] google.auth.transpor [DEBUG   ] Making request: GET http://169.254.169.254
[2019-11-19 …
```
=> Ignore errors marked for ignoring in the activities (auth piggybacking)

kopf/clients/auth.py, kopf/clients/discovery.py, kopf/clients/fetching.py, kopf/clients/patching.py, kopf/clients/watching.py, kopf/structs/resources.py, tests/conftest.py, tests/k8s/conftest.py
> Issue : #249 
> Broken in #227
`pykube-ng` did a discovery of the resources and cached them in memory, so it knew which resources are namespaced, which are cluster-scoped — and generated the URLs accordingly.
When switched to `aiohttp`, this discovery logic was lost, so all URLs became either cluster-scoped (by default) or namespaced (if the operator had `--namespace` defined). 
The only thing broken is the cluster-scoped resources in the namespaced operators: they could not be reached (404 Not Found), because they do not exist in the namespaces.
**This is a hot-fix for 0.23. No unit-tests — to be added later. Tested manually in presumably all combinations in Minikube — now, it works as it was before 0.23.**
=> Hot-fix the cluster-scoped resource discovery in namespaced operators

kopf/clients/auth.py, kopf/clients/discovery.py, tests/authentication/test_reauthentication.py, tests/k8s/test_discovery.py
> Issue : #251 
While testing a hotfix in #250 for #249, even without the KopfPeering CRDs defined, it happened so that the group-version did exist, since the KopfExample CRD of the same `zalando.org/v1` group-version was defined.
When none of the `zalando.org/v1` CRDs exist, the operator fails with 404 on startup unless in `--standalone` mode. — **This affects the first user experience and a quick-start guide scenario.**
This PR fixes this issue: 404 (and 403) in the resource discovery, i.e. absence of the group-version, are treated same as the absence of the individual resources while the group-version exists.
In addition, this PR adds some tests that were missing in #250 due to urgency.
_List of tasks the reviewer must do to review …
=> Peerings not found when zalando.org/v1 group is absent

requirements.txt
The type-checking rules should be predictable over time.
> Issue : originally detected in #262, originally introduced in #200 
New `mypy` releases sometimes break the CI/CD builds when no significant code changes are introduced to the codebase. The CI/CD builds are expected to succeed as before.
Just happened in #262 — a documentation/CRD change, that got `asyncio.wait()` type-checks in `kopf.reactor.running` broken. A broken build: https://travis-ci.org/zalando-incubator/kopf/builds/620169471
Caused by a regression in `mypy==0.750` with type inference (https://github.com/python/mypy/issues/8051). The fix is going to be released 1 month after the regression was introduced: 21.11.2019 .. 16.12.2019. We cannot afford to wait 1 month with a broken CI/CD pipeline.
Previously, there were …
=> Ensure predictable mypy's type-checking rules in CI/CD

tools/minikube-for-travis.sh
> Issue : #269 
Minikube is broken with K8s 1.17.0+RBAC.  The related Minikube issue is linked in #269. 
Authorization is changed from "RBAC" to "Node,RBAC".  This PR will allow us to continue with the development. 
Originally, RBAC-only mode was enabled to ensure that the operators are runnable in our RBAC-only environment, and the default Kubernetes authorization mode "Node,RBAC" was false-positive in some cases (back then in ~Apr'2019), so the issues were noticed only during the deployments to a RBAC-only environment.
By disabling this mode, we can get those false-positive test results again (RBAC-related). But this is the only way to make it run in CI/CD.
_PS: "False-positives" in this cases means that something can be actually broken for the RBAC-only environment, but the tests do …
=> [269] Fix broken CI/CD tests due to Minikube w/ K8s 1.17.0 + RBAC

docs/errors.rst, examples/03-exceptions/example.py, kopf/on.py, kopf/reactor/handling.py, kopf/reactor/registries.py, requirements.txt, tests/basic-structs/test_handlers_deprecated_cooldown.py, tests/registries/test_decorators.py, tests/registries/test_decorators_deprecated_cooldown.py
Fix a terminology issue, but keep it backward compatible.
> Issue : #222, #16
Due to my not so good English vocabulary, a slightly inappropriate word was used for the delay between retries of the handlers in #222: "cooldown". 
"Cooldowns" are used in the RPG games for the spells. In Computer Science, the proper word would be ["backoff"](https://en.wiktionary.org/wiki/backoff): 
* [exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff), 
* [`retry` library's `backoff=` kwarg](https://github.com/invl/retry#retry-decorator), 
* Kubernetes pods' `CrashLoopBackOff`, 
* Kubernetes jobs' [`spec.backoffLimit`](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#pod-backoff-failure-policy),
* etc.
It is better to fix this terminology issue before it …
=> Rename "cooldown" to "backoff" for handler retrying

kopf/cli.py, kopf/engines/peering.py, kopf/reactor/activities.py, kopf/reactor/handling.py, kopf/reactor/running.py, kopf/structs/credentials.py, kopf/structs/primitives.py, requirements.txt, tests/authentication/test_authentication.py, tests/authentication/test_vault.py, tests/conftest.py, tests/handling/test_cause_handling.py, tests/handling/test_cause_logging.py, tests/handling/test_delays.py, tests/handling/test_errors.py, tests/handling/test_event_handling.py, tests/handling/test_freezing.py, tests/handling/test_multistep.py, tests/handling/test_no_handlers.py, tests/handling/test_retrying_limits.py, tests/primitives/test_flags.py, tests/primitives/test_toggles.py
> Issue : #255 
The existing coroutines to handle the existing synchronisation primitives (a generalised **flag**) are moved to the dedicated module, and tests are added (previously it was considered an implementation details and not tested directly).
A new synchronisation primitive is added to simplify the code and reduce the semantical complexity of the logic by removing the technical low-level details from it:
A **toggle**, which is like an event, but is bi-directional: can be turned on/off, and can be awaited until turned on/off — unlike the events, which can be awaited only until turned on, but not off.
- Refactoring
=> Refactor the synchronisation primitives

examples/crd.yaml
Signed-off-by: Nicolas Kowenski <nicolas.kowenski@id.ethz.ch>
> Issue : #261
The JSONPath was missing the function name create_fn
=> Fix bug #261, JSONPath should include the function name

requirements.txt
Resolve `coveralls` vs. `pytest-cov` battle for `coverage` versions due to `coverage==5.0` release 2 days ago.
> Issue : closes #272 
`coverage==5.0` has been release on 14.12.2019 (2 days ago). This broke the CI/CD, as pip cannot resolve the version conflict: 
* `pytest-cov` wants `coverage>=4.4`, and is executed first.
* `coverage==5.0` is found and installed.
* `coveralls` wants `coverage<5.0`, but it is too late to reinstall.
The fix is to install `coverage<5.0` before any of the dependencies request it. The solution is temporary by its nature. See #273 for a more generic approach (version pinning and auto-upgrading) — will be done somewhen later.
=> [272] Enforce the version of `coverage` manually (pip fails to resolve)

kopf/clients/watching.py, tests/k8s/test_watching.py, tests/k8s/test_watching_iterjsonlines.py, tests/k8s/test_watching_iterlines.py
Parse the JSON lines of Kubernetes watch-streams with no memory limit.
> Issue : #275
Kubernetes can send JSON lines with huge objects. E.g., secrets of 2MB in #275. 
`aiohttp` has a hard-coded limit the lines received from the stream, and it is 128KB ([`aiohttp.streams.DEFAULT_LIMIT = 2**16`](https://github.com/aio-libs/aiohttp/blob/6a5ab96bd9cb404b4abfd5160fe8f34a29d941e5/aiohttp/streams.py#L20) = 64 KB for the low watermark of the buffer, multiplied by 2x for high watermark, where the exception is raised).
There is no way to externally configure the buffer size of the aiohttp's StreamReader, so as there is no way to inject our own `StreamReader` instances with `limit=` properly set. The [docs say](https://docs.aiohttp.org/en/stable/streams.html):
> User should never instantiate streams …
=> [275] Parse JSON lines ourselves to avoid aiohttp's "Line is too long"

kopf/reactor/handling.py, kopf/reactor/states.py, tests/handling/test_timing_consistency.py
Fixes an issue with time discrepancies that stopped the reaction cycle if the operator was unlucky enough to hit the scheduled awakening time with 1ms precision.
Previously, "now" of `handler.awakened` and "now" of `state.delay` were different (maybe for less than 1 ms). If the scheduled awakening time was unlucky to be between these two points in time, the operator stopped reacting on this object until any other events or changes arrive.
Specifically, the operator neither selected the handlers to be executed (because it was "1ms too early" for the `handler.awakened`), nor did it sleep (because it was "1ms too late" in the `state.delay` property) — with the same value of `delayed` field, just the code being executed exactly during this awakening time.
Due to how zero-time delay is treated …
=> Distinguish "no handlers at all" and "no handers for now" cases

kopf/clients/auth.py, kopf/clients/discovery.py, kopf/clients/events.py, kopf/clients/fetching.py, kopf/clients/patching.py, kopf/clients/watching.py, setup.py, tests/authentication/test_credentials.py, tests/authentication/test_reauthentication.py, tests/authentication/test_tempfiles.py, tests/conftest.py
`aiohttp` v4 _would_ bring few changes incompatible with Kopf and _would_ break both the CI/CD pipelines and the Kopf-based operators. Some of these issues can be proactively fixed now. Others can be prevented by non-upgrading to v4.
> Issue : closes #246
The main incompatibility is that it is now impossible to inherit from `aiohttp.ClientSession` — explicitly restrictred in `aiohttp`. 
This PR converts our `APISession` from inheriting `aiohttp.ClientSession` to containing  `aiohttp.ClientSession` (i.e. a composition instead of inheritance). 
Since it is not a _session_ anymore, it is also renamed to a _context_ — the closest semantic equivalent I could find. Nevertheless, it is not part of the public interface, so we are free to change and rename it as needed.
_Beside of that, it also …
=> [246] Prepare for aiohttp v4, but stay with v3

kopf/reactor/causation.py, kopf/reactor/handling.py, tests/causation/test_detection.py, tests/handling/conftest.py, tests/handling/test_cause_handling.py, tests/handling/test_no_handlers.py
In https://github.com/zalando-incubator/kopf/pull/258 we talked about how there was a bit of a chicken and the egg situation with requires_finalizer. You proposed pulling the the requires_finalizer detection into `handle_resource_changing_cause` (option B).
This pull request implements option B from that discussion, as I understood it.
The need to add or remove a handler was detected in `detect_resource_changing_cause` in causation.py.
The need to add or remove a handler will be detected in `handle_resource_changing_cause` in handling.py.
N/A
Internal.
@nolar presented 2 possible options in another PR, this is the 2nd option.
Not that I can see, but i am not familiar with this code.
> Issues: 
> Related:
https://github.com/zalando-incubator/kopf/pull/258
- Refactoring (non-breaking change …
=> Remove Reason.ACQUIRE and Reason.RELEASE

docs/handlers.rst, examples/11-filtering-handlers/example.py, examples/11-filtering-handlers/test_example_11.py, kopf/on.py, kopf/reactor/handling.py, kopf/reactor/invocation.py, kopf/reactor/registries.py, kopf/toolkits/legacy_registries.py, tests/registries/legacy/test_legacy_decorators.py, tests/registries/legacy/test_legacy_requires_finalizer.py, tests/registries/test_decorators.py, tests/registries/test_handler_matching.py, tests/registries/test_requires_finalizer.py
> Issue : #98
In some cases, it might be needed that only a subset of resources are handled. An example might be implementing the cert-manager external issuer process where cert-manager creates a CertificateRequest CRD and waits for it to be acted on and marked as complete, and each issuer should filter on `spec.issuerRef` to find the requests it should service.
This PR enables that use case by allowing you to specify a `when` callback that is run before invoking a handler to filter out handlers that are not appropriate.
=> Filter by arbitrary callback function

docs/walkthrough/resources.rst
documentation update to ensure that names.kind, names.plural, names.singular and names.shortNames can be used. names.singular was missing in the documentation
No code changes, only a simple doc update to illustrate that a crd's names.singular field
also can be used in kubectl get 
No behaviour change
yes only the doc portion
None
> Issues: #12 
> Related:
- Mostly documentation and examples (no code changes)
=> documentation update: we can use names.singular as well in kubectl get

README.md, examples/04-events/example.py, examples/13-hooks/example.py, kopf/clients/auth.py, kopf/on.py, kopf/reactor/running.py
Improve the codebase to resolve the remaining LGTM's warnings and some of the recommendations.
LGTM itself is enabled via GitHub actions/integrations, so no code changes are needed.
LGMT is a code quality control tool (one of them) — as in "looks good to me": https://lgtm.com/
This project's analysis can be previewed at https://lgtm.com/projects/g/zalando-incubator/kopf/
The code logic is changed in few places — presumably, with no behavioural changes (just try-except-else restructuring to a flat code).
> Issues: #13 
- Mostly CI/CD automation, contribution experience
=> Enable LGTM checks and fix few LGTM alerts

kopf/clients/events.py, kopf/reactor/callbacks.py, kopf/reactor/queueing.py, kopf/reactor/running.py, kopf/reactor/states.py, tests/k8s/test_events.py
Prevent leaking `Authorisation:` and maybe other sensitive headers of the K8s API requests and responses when failing to post an event.
Previously, Kopf was logging the whole repr of an error in case of failures.  With `aiohttp.ClientResponseError`, this seems to be a problem, as its repr includes all the request headers, including `Authorization: …`. 
When this header is logged, then those who have access to the logs can also get access to the K8s API (especially if the K8s API tokens are not expired, which is the case on its own).
With this change, it will only show string forms of any errors.  For `aiohttp.ClientResponseError`, this means only the HTTP status, message, and an URL. And, as a special case, in K8s-event posting, only the HTTP status and message.
> Issues: fixes #305
- Bug …
=> [305] Hide authorisation headers of exceptions' reprs

kopf/clients/auth.py, kopf/clients/discovery.py, kopf/clients/patching.py, kopf/structs/resources.py, tests/basic-structs/test_resource.py, tests/conftest.py, tests/k8s/test_discovery.py, tests/k8s/test_patching.py
Patch custom/built-in resources with status declared as a sub-resource via a separate URL — instead of being a field of a resource itself.
Previously, Kopf always assumed that custom resources and built-in resources store status as part of the object (which was the case in early Kubernetes versions).
But this has changed since [sub-resources were introduced](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#subresources). While it was not a big problem for custom resources, where the developers could define the sub-resources and skip "status" there, it became a problem with some built-in resources like "storage.k8s.io/volumeattachments", which have the status defined as a sub-resource and operator developers cannot control it.
As a …
=> Patch status as a sub-resource if defined so

README.md
When the Dockerfile mentioned here is copied as is, it does not run the container as the path inside the container is incorrect. Fixing that
Reflects the correct Dockerfile doc to be used
Incorrect path in README.doc
Enhanced UX
N/A
End-users
N/A
No
- Mostly documentation and examples (no code changes)
=> Update the Dockerfile to fix the handlers.py path inside container

.travis.yml, kopf/reactor/running.py, kopf/structs/credentials.py, kopf/structs/primitives.py, tests/conftest.py, tests/posting/conftest.py, tests/primitives/test_toggles.py
Switch from Python 3.7 to 3.8 as the primary testing environment in Travis, and resolve few issues/warnings with 3.8. Python 3.7 compatibility is still tested and ensured.
The testing is now organised this way:
* The latest Python — with all supported Kubernetes versions.
* The latest Kubernetes — with all supported Python versions (3.7 & 3.8 & optionally 3.9-dev).
We assume that if something breaks, it either breaks in the language (and one K8s version is enough to detect it), or in Kubernetes API (and one Python version is enough to detect it) — there is no need to test a real matrix "all Pythons vs. all K8ses".
Travis CI has a limit of 5 builds running in parallel (for us), so more than 5 or 10 builds delays the build results. Currently, we have 10 — and so it will be with the new grid …
=> Switch to py38 as the primary CI version, keep py37 tested

kopf/reactor/handling.py, kopf/reactor/invocation.py, kopf/reactor/registries.py, kopf/reactor/running.py
Prevent leakage of OS resources (threads) on operator existing, which can make it irresponsive after the main function is finished and no logging is happening (if a sync-handler hangs).
All sync-handlers (declared with `def`, not `async def`) are executed in thread pools. The operator itself is fully asynchronous. Whenever operator is exiting or is being cancelled, it also cancels all its coroutines. However, if a coroutine is cancelled at `loop.run_in_executor()`, the coroutine indeed exits, but the thread it used continues running — until finished. As a result, some threads can continue running even after the operator is kind-of-exited normally.
This becomes critical as long-running handlers are coming into play (i.e. daemons). But it is a change of its own value even now — hence, it is …
=> Prevent thread leakage on exiting

kopf/on.py, kopf/reactor/handlers.py, kopf/reactor/handling.py, kopf/reactor/invocation.py, kopf/reactor/registries.py, kopf/structs/callbacks.py, kopf/toolkits/legacy_registries.py, tests/basic-structs/test_handlers.py, tests/basic-structs/test_handlers_deprecated_cooldown.py, tests/handling/test_no_handlers.py, tests/registries/conftest.py, tests/registries/test_handler_matching.py
Move the code around and rename some types & classes for callbacks & handlers.
No user-facing changes.
This is the last preparing PR before the daemons & timers PR (#330).
Here, we just move the code around and rename classes. It would be messy to have these in the daemons & timers PR, so it goes separately.
Specifically, the resource-related handlers are split into resource-changing & resource-watching — same as it is already done for registries. These handlers & callbacks are de factor different anyway, but were declared as the same for laziness reasons. In the daemons & timers PR, also resource-spawning handlers & daemon/timer callbacks will be added with their own signatures.
No behavioural changes, no user-facing changes.
> Issues: #19 
- Refactoring (non-breaking change which does …
=> Split handers & callbacks types for resource-related handlers

kopf/clients/watching.py, kopf/config.py
allow to set a custom timeout when making the `GET ..?watch=true` request to Kubernetes API if needed.
Currently the timeout is always None, which we find to be a reason for issues like #204 .
With this patch controller authors may override the timeout passed by kopf to the underlying aiohttp session request by doing something like this in their controller code:
```
import kopf
kopf.config.WatchersConfig.session_timeout = 10.0
@kopf.on(..)
def handler(*):
....
```
The default behavior is not changed.
Issues: #204 
=> Allow for custom timeout in watch request

.travis.yml
Fix the CI/CD tests with Kubernetes 1.18, which now requires `conntrack`.
Since Kubernetes 1.18 release ([since 25.03.2020](https://kubernetes.io/blog/2020/03/25/kubernetes-1-18-release-announcement/)), the CI/CD tests are broken:
```
error execution phase preflight: [preflight] Some fatal errors occurred:
[ERROR FileExisting-conntrack]: conntrack not found in system path
```
This PR fixes it.
> Issues:  fixes #334 
- Mostly CI/CD automation, contribution experience
=> Install conntrack to pass CI/CD with K8s 1.18

docs/handlers.rst
`do duplicating side-effects` -> `no duplicating side-effects`
> Issues: #12 
> Related:
- Refactoring (non-breaking change which does not alter the behaviour)
- Mostly documentation and examples (no code changes)
=> Fix small typo in handlers.rst

docs/configuration.rst, examples/09-testing/test_example_09.py, examples/11-filtering-handlers/test_example_11.py, kopf/clients/watching.py, kopf/structs/configuration.py, tests/e2e/test_examples.py, tests/reactor/test_queueing.py, tests/settings/test_defaults.py
Follow-ups for #336 with better naming of the timeout settings.
#336 was merged but not released yet, so it is fine to quickly change the names without backward compatibility implemented.
In addition, a connection timeout is added for watching streams — to distinguish it from the total timeout on the client side (which is supposed to be infinite in a perfect world). The connection timeout is needed to handle the cases of broken networking in some cluster setups — for which `kopf.config.WatchersConfig.session_timeout` was originally introduced in #322 .
> Issues: #23
> Related: #322 #192 #109
- Mostly documentation and examples (no code changes)
=> Better naming for timeouts + connection timeout

kopf/__init__.py, kopf/reactor/causation.py, kopf/reactor/daemons.py, kopf/reactor/processing.py, kopf/structs/containers.py, tests/basic-structs/test_containers.py, tests/hierarchies/test_contextual_owner.py, tests/lifecycles/test_real_invocation.py
Publishes all object types which are exposed to the user-side: as handlers' kwargs or as overridable classes.
This was actually promised in #194, but not actually implemented.
With these types exposed, the users can type-annotate the kwargs, making them friendly in the IDEs, or or to type-check their operators. It is more wordy than in the examples/docs, but this is how type annotations generally work:
```python
from typing import Any
import kopf
@kopf.on.create('zalando.org', 'v1', 'ephemeralvolumeclaims')
def create_fn(
spec: kopf.Spec, name: str, namespace: str, patch: kopf.Patch,
logger: kopf.ObjectLogger, **_: Any):
...
```
Another group of classes exposed are those supposed to be used in the overridden/inherited classes, such as persistence storage classes: the storage classes were …
=> Publish types for kwargs/classes exposed to the user-side

kopf/reactor/registries.py, tests/registries/test_handler_matching.py
Fix an issue with not calling the field-handlers if the change is too big/generic (regression).
This issue was once fixed in #191. Since then, the handler selection was moved to other functions and places, and that logic was not reproduced.
The issue happens when there is a handler for a field, and a diff is too big and generic, not specific to sub-fields. For example:
```python
import kopf
@kopf.on.field(..., field='metadata.labels')
def propagate_labels(diff, **_):
pass
```
And the diff is:
```python
[('add', ('metadata', 'labels'), None, {'x': 'y'}))]
```
This can happen when the labels are added to an object which previously had no labels. If it had any other labels, it is all fine, since the diff becomes specific only to the new labels:
```python
[('add', ('metadata', 'labels', 'x'), …
```
=> Fix on-field handler selection when a field is longer/equal to a diff

docs/daemons.rst, docs/errors.rst, docs/index.rst, docs/tips-and-tricks.rst, examples/14-daemons/example.py, kopf/reactor/daemons.py, kopf/reactor/processing.py, kopf/reactor/registries.py, kopf/structs/containers.py, kopf/structs/primitives.py, kopf/toolkits/legacy_registries.py, tests/handling/daemons/test_daemon_rematching.py
Run daemons only as long as they match the filtering criteria, making the daemon's filters continuously evaluated. Stop and re-spawn the daemons as soon as they stop or start matching the criteria (any number of times).
While implementing an operator for EphemeralVolumeClaim resource (which is also Kopf's tutorial) with Kopf 0.27rc1, it has become clear that the newly introduced daemons (#330) have ambiguous behaviour when combined with filters: they were spawned only on the resource creation or operator startup, and never re-evaluated even when the criteria changes or the resource stops matching the criteria.
This problem didn't exist with the regular short-run handlers, as they were selected each time the changes/events happened, and never existed for long time.
This PR brings the …
=> Run daemons only as long as they match the filtering criteria

kopf/reactor/processing.py, kopf/storage/progress.py, tests/handling/test_cause_handling.py, tests/persistence/test_storing_of_progress.py
Trigger the after-sleep handling cycles via the progress storage, the same way as it is triggered for the no-sleep handlers.
This aspect was unintentionally forgotten in #331, where the handlers' persistence was made configurable.
If the resource would have no arbitrary field preservation (e.g. for built-in resources), the dummy patching would be silently ignored by K8s API. 
With this PR, the dummy patches are made the same way as the regular handlers are patched, so the handling cycles are always provoked after the sleeps.
> Issues: #308 #23 #283 #321 
> Related: #331 
=> Provoke handling cycles even with no arbitrary field preservation

docs/configuration.rst, kopf/reactor/causation.py, kopf/reactor/processing.py, kopf/storage/finalizers.py, kopf/structs/configuration.py, tests/causation/test_detection.py, tests/handling/conftest.py, tests/handling/daemons/test_daemon_errors.py, tests/handling/daemons/test_daemon_filtration.py, tests/handling/daemons/test_daemon_termination.py, tests/handling/daemons/test_timer_errors.py, tests/handling/daemons/test_timer_filtration.py, tests/handling/test_cause_handling.py, tests/handling/test_delays.py, tests/test_finalizers.py
Make finalizer's name configurable, thus allowing multiple operator with different identities to handle the same resources with advanced handlers (anything different than `on.event`).
As a side-effect of #331, the operator gained possibility to change its own identity by using different prefixes or fields instead of the hard-coded Kopf's names/domains. This allowed multiple operators handling the same resources with advanced handlers (anything different than `on.event`; e.g. `on.create`, `on.update`, `on.delete`, etc; also, `kopf.daemon` & `kopf.timer`).
However, only one finalizer was used for all operators: `kopf.zalando.org/KopfFinalizerMarker` (hard-coded). This could lead to different operators possibly colliding with each other.
With this PR, it is now possible to also configure the …
=> Make finalizer's name configurable

docs/filters.rst, kopf/__init__.py, kopf/structs/callbacks.py, tests/test_filtering_helpers.py
Little helpers to combined few callbacks for `when=` or labels/annotations filters.
Nothing more that a little bit of syntax sugar with `kopf.all_()` and `kopf.any_()`:
```python
import kopf
def whole_fn1(name, **_): return name.startswith('kopf-')
def whole_fn2(spec, **_): return spec.get('field') == 'value'
def value_fn1(value, **_): return value.startswith('some')
def value_fn2(value, **_): return value.endswith('label')
@kopf.on.create('zalando.org', 'v1', 'kopfexamples',
when=kopf.all_([whole_fn1, whole_fn2]),
labels={'somelabel': kopf.all_([value_fn1, value_fn2])})
def create_fn1(**_):
pass
@kopf.on.create('zalando.org', 'v1', 'kopfexamples',
when=kopf.any_([whole_fn1, whole_fn2]),
labels={'somelabel': kopf.any_([value_fn1, value_fn2])})
def create_fn2(**_):
pass
```
Based on the …
=> Provide helpers to combine few callbacks for body-/meta-filters

kopf/storage/progress.py, tests/persistence/test_annotations_hashing.py
An issue found the hard way (though we hit it before): when an annotation's name is 64 or more characters, it is not accepted by K8s API. This is [documented](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set).
For example if we have a prefix, a long function name, and maybe a field suffix: `kopf.zalando.org/some_resource_of_interest_created.status.childname` — and oops, it is 67 already, while 63 is allowed.
This PR fixes the issue with lengthy handler ids by cutting their tail, and replacing it with some consistent one-way hash — this makes the annotation unique enough, and still recognisable/readable for the primary part of its name.
> Issues: #331 
=> Limit persistence annotations to 63 chars

requirements.txt, tests/conftest.py
Fix CI/CD tests with pytest-asyncio and no explicit declaration of `event_loop` fixture (as it is not used). This only affects CI/CD and local development, not the framework itself.
Blocks #350 #351 and all new PRs.
**Part 1:** Reveals itself as async tests freezing with no reaction for long time: due to fixtures (e.g. aresponses, aiohttp server, etc) created in different event loops than the test itself. 
Originally caused by pytest-asyncio upgrade from 0.10.0 to 0.11.0 ([diff](https://github.com/pytest-dev/pytest-asyncio/compare/v0.10.0...v0.11.0)).
Fixed by auto-adding `asyncio` markers for all async tests even earlier than before, so that pytest-asyncio could notice them on item creation.
---
**Part 2:** In that case, some tests fail due to event loop is not running when they try to …
=> Fix async tests with no explicit `event_loop` usage/declaration

kopf/storage/progress.py, tests/persistence/test_annotations_hashing.py
Force annotation names to end strictly with alphanumeric characters, not only to fit into 63 chars.
_"Learning Kubernetes the hard way."_
The annotation names are not only limited to 63 characters, and not only to a specific alphabet, but also to the beginning/ending characters. Otherwise, it fails to patch:
```
$ kubectl patch … --type=merge -p '{"metadata": {"annotations": {"kopf.zalando.org/long.handler.id.here-WumEzA--": "{}"}}}'
The … is invalid: metadata.annotations: Invalid value: "kopf.zalando.org/long.handler.id.here-WumEzA--": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
```
Since …
=> Force annotations to end strictly with alphanumeric characters

.travis.yml
Fix sporadic issues with coveralls API: either 500s, or 422 Unprocessable Entity — by ignoring them.
It fails often with HTTP 422 Unprocessable Entity when posting results, especially after the retries. Make it optional. E.g. https://travis-ci.org/github/zalando-incubator/kopf/jobs/684865883
This might damage the assumulated coverage data, but failing our builds with no way of retrying (without fake commits) is more troublesome.
Sometimes, it fails with 5xx due to API overload. Retrying would be fine, but then it hits 422.
> Issues:  #99 
- Mostly CI/CD automation, contribution experience
=> Make coveralls optional in CI builds

kopf/reactor/daemons.py, kopf/reactor/processing.py, kopf/structs/configuration.py, kopf/structs/containers.py, tests/handling/daemons/test_daemon_errors.py, tests/handling/daemons/test_daemon_termination.py
Fix an issue in 0.27rc5 when resource deletion hangs for daemons/timers combined with other handlers — due to not allowing them a fair chance to exit instantly, despite they can.
Previously, when a daemon/timer was capable of exiting instantly, it didn't have enough event loop cycles to do that — only one cycle was given with only one `asyncio.sleep(0)`, while there could be a few `await` calls both in the daemon itself and in the framework's wrapping routines (even if it is zero-time, `await` gives control back to the event loop). 
This is especially important for timers, which spent most of their time in sleeping until the next trigger, so they definitely can exit instantly, but didn't have a chance due to 2-3 `await` uses internally.
Now, Kopf will give 10 zero-time asyncio cycles to …
=> Wait for instantly exiting daemons/timers for more than one asyncio cycle

kopf/storage/states.py, tests/handling/conftest.py, tests/handling/test_multistep.py
Fix a bug when the finalizer was removed after the 1st deletion handler, preventing the 2nd and other deletion handlers from being invoked. 
This was not an issue for other (non-deletion) handlers.
Due to a recent change of criteria of "done" for handlers from "when done and reason=DELETE" to "when no delays left and deletionTimestamp is there" (commit 7adba026d949f9fe8d3b1420e296161b5eb207c3, PR #330), the actual "done" criterion was not used. The delays were empty all the time, which was mistakenly treated as "all is done".
With this fix, the unfinished (but not delayed) handlers will report a required delay of 0 seconds (meaning "try me immediately"). This, in turn, will prevent finalizers removal until all handlers are finished (i.e. none of them reported even a 0 delay).
> Related: …
=> Prevent premature finalizers removal for 2+ deletion handlers

kopf/storage/progress.py
Fix a _potential_ bug when unnecessary state purging could prevent the following handling cycles from happening.
This bug was not detected in practice (probably), but it could happen so that purging of a persisted annotation with a handler's state (by patching it with `None`) could lead to actual absence of changes on the server side if that annotation was already absent, but preventing a dummy-patch to be applied in Kopf because the main patch is not empty.
This, in turn, could lead to no watch-events reported by Kubernetes API (as nothing has changed), and Kopf would not react with the following steps until the next (probably unrelated) change.
Now, with this fix, if the annotation is already absent in the body, it will not be nullified in the patch, letting a dummy-patch to be applied …
=> Avoid purging the annotations that are already absent
